### ISSUE TITLE
Doesn't run with Linux

### ISSUE THREAD

**Issue by johmicrot** [thevickypedia/stress_injector#1]
Running v0.3.2.   

The problem is [here](https://github.com/thevickypedia/stress-injector/blob/7a7d530f940e55e29fe42b486a4dcb3dc90df8ba/stressinjector/memory.py#L99)

I'm running Ubuntu 20.04

The line says "if operating_system == 'Darwin':" .  I changed "Darwin" to "Linux" and the code ran, but it looks like there is another error with reporting the memory with Linux.  

Stress Injected: 4.0 GB
Actual memory Consumed: 4.03 MB

**Comment by thevickypedia** [comment]
I didn't get a chance to test this package on Linux until now, that's the reason why the OS specific conditions were put in place.
The problem you're describing is because the memory usage is formatted as kilobytes in Linux
More on it in [docs page](https://man7.org/linux/man-pages/man2/getrusage.2.html) under title `ru_maxrss`
The new [version 0.4](https://pypi.org/project/stress-injector/0.4/) supports Linux now
